### ISSUE TITLE
Create missing tests

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_automated_ingest#63]
- [x] Non-utf8-encodable filenames for register_as_replica_sync (see https://github.com/irods/irods_capability_automated_ingest/issues/251)
- [x] Non-utf8-encodable filenames for put_sync
- [x] Non-utf8-encodable filenames for put_append
- [x] Chunking/files_per_task logic (see https://github.com/irods/irods_capability_automated_ingest/issues/252)
- [x] File name/directory exclusion (filename exclusion test added in c508e17111d8b2fc24a1235b59fed36a77bd6c76) (see https://github.com/irods/irods_capability_automated_ingest/issues/253 for `--exclude_directory_name`)
- [x] Special file types (symlinks, sockets, pipes, etc.) (see https://github.com/irods/irods_capability_automated_ingest/issues/204)
- [x] Symlinks to directories (https://github.com/irods/irods_capability_automated_ingest/issues/254)
- [x] `--profile` option (see https://github.com/irods/irods_capability_automated_ingest/issues/255)

Add more as needed

**Comment by alanking** [comment]
For documentation purposes...

Evaluating missing tests can be improved via a tool like [coverage.py](https://coverage.readthedocs.io/en/v4.5.x/). Using coverage is easy enough, but I am currently running into issues with tracing code invoked via `subprocess`. There are [instructions for measuring sub-processes](https://coverage.readthedocs.io/en/coverage-4.2/subprocess.html).

**Comment by alanking** [comment]
Instructions for getting Coverage running...

For now, need custom install of coverage with checkout at this commit: https://github.com/elyezer/coveragepy/commit/fa2a94dccb34b017035ccb819b037cab88ff492f
Provides monkeypatch for Billiard hook in coverage module
Post detailing process for change above... https://www.redhat.com/archives/pulp-dev/2016-August/msg00018.html
gist with instructions for running tests... https://gist.github.com/elyezer/2d8225843451364cbb19af08f4f52de3
Celery has stated that version 5 will be replacing Billiard with something else: https://github.com/celery/celery/issues/3422#issuecomment-358974274

Follow steps here to set up coverage for subprocess: https://coverage.readthedocs.io/en/v4.5.x/subprocess.html

Need to have COVERAGE_PROCESS_START set to config file path:
```
export COVERAGE_PROCESS_START=/path/to/.coveragerc
```
OR, in the test file...
```
os.environ['COVERAGE_PROCESS_START'] = '/path/to/.coveragerc'
```
Options for config here: https://coverage.readthedocs.io/en/v4.5.x/config.html#config
Needs the following:
```
# .coveragerc to control coverage.py
[run]
parallel = True
concurrency=multiprocessing
include=*/irods_capability_automated_ingest/* # optional - reduces noise in the report
```

Celery workers must be started with solo concurrency pool option to receive coverage:
```
celery worker -A irods_capability_automated_ingest.sync_task -P solo <other options>
```
Only runs a single process for everything, causes hang when ending Celery worker for some reason.
Possible improvement of performance until we find a fix would be to reduce the timeout window for an iRODS session (defaults to 60 seconds).
For more info on the pools: https://www.distributedpython.com/2018/10/26/celery-execution-pool/

Run tests like this:
```
coverage run -m irods_capability_automated_ingest.test.test_irods_sync <specific test args...>
coverage combine # combine all reports generated by different processes
coverage report  # show table with coverage percentages
```

**Comment by alanking** [comment]
Using modifications above based on master at time of writing, I generated the following report for the project:
```
Name                                                                         Stmts   Miss  Cover
------------------------------------------------------------------------------------------------
irods_capability_automated_ingest/__init__.py                                    0      0   100%
irods_capability_automated_ingest/core.py                                       25      7    72%
irods_capability_automated_ingest/examples/__init__.py                           0      0   100%
irods_capability_automated_ingest/examples/append.py                             5      0   100%
irods_capability_automated_ingest/examples/append_json.py                        8      1    88%
irods_capability_automated_ingest/examples/append_root_with_resc_name.py         7      0   100%
irods_capability_automated_ingest/examples/no_op.py                              5      0   100%
irods_capability_automated_ingest/examples/no_retry.py                          16      0   100%
irods_capability_automated_ingest/examples/post_job.py                           9      0   100%
irods_capability_automated_ingest/examples/pre_job.py                            9      0   100%
irods_capability_automated_ingest/examples/put.py                                5      0   100%
irods_capability_automated_ingest/examples/put_root_with_resc_name.py            7      0   100%
irods_capability_automated_ingest/examples/put_with_resc_name.py                 7      0   100%
irods_capability_automated_ingest/examples/register.py                           5      0   100%
irods_capability_automated_ingest/examples/register_root_with_resc_name.py       7      0   100%
irods_capability_automated_ingest/examples/register_with_resc_name.py            7      0   100%
irods_capability_automated_ingest/examples/replica_root_with_resc_name.py        7      0   100%
irods_capability_automated_ingest/examples/replica_with_resc_name.py             7      0   100%
irods_capability_automated_ingest/examples/retry.py                             20      0   100%
irods_capability_automated_ingest/examples/sync.py                               5      0   100%
irods_capability_automated_ingest/examples/sync_root_with_resc_name.py           7      0   100%
irods_capability_automated_ingest/examples/timeout.py                           10      0   100%
irods_capability_automated_ingest/irods_sync.py                                102      6    94%
irods_capability_automated_ingest/sync_irods.py                                330     48    85%
irods_capability_automated_ingest/sync_logging.py                               45      4    91%
irods_capability_automated_ingest/sync_task.py                                 474    176    63%
irods_capability_automated_ingest/sync_utils.py                                 88      3    97%
irods_capability_automated_ingest/test/__init__.py                               0      0   100%
irods_capability_automated_ingest/test/test_irods_sync.py                      700    136    81%
irods_capability_automated_ingest/utils.py                                      22      5    77%
------------------------------------------------------------------------------------------------
TOTAL                                                                         1939    386    80%
```
I've also attached a .zip which contains the html report: [htmlcov.zip](https://github.com/irods/irods_capability_automated_ingest/files/2703803/htmlcov.zip)

**Comment by alanking** [comment]
I've created individual issues for the remaining tests. Closing this one.
